fix(gradle) : jwt token, login, signUp, emailCheck, login 테스트 api 추가 완료
Forever-Pet/foreverpet-backend pull request #109
Opened 2023-08-07 09:31 UTC by AiRn33

로그인 및 jwt 토큰 추가 완료

2023-08-07 15:34 UTC, cmong0516 requested changes
고생하셨습니다
전에 제가 구현한거랑 다른방법들이 있어서 잘 봤습니다
몇몇부분 코멘트 남겨드렸습니다!

2023-08-07 15:34 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/service/CustomUserDetailsService.java
> +    private org.springframework.security.core.userdetails.User createUser(String username, UserInfo user) {
CustomUserDetails 를 만들어서 구현했었는데
여기에 바로 구현할수도 있군요

2023-08-07 15:34 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/service/UserService.java
> +                .authorityName("ROLE_USER")
하드코딩 하지 않고 Authorities 라는 Enum 을 만들어서 USER GUEST ADMIN 등을 추가하는건 어떠신가요 ?

2023-08-07 15:34 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/service/UserService.java
> +        Long userNo = userInfoJpaRepository.save(user).getUserNo();
userNo 보단 명확하게 userId or userNumber 가 좋을거같습니다!

2023-08-08 08:13 UTC, AiRn33 commented on src/main/java/com/hello/foreverpet/config/SecurityUtil.java
> +    private SecurityUtil() {}
생성자가 필요없네요 체크를 못했습니다 ㅠ

2023-08-08 08:13 UTC, AiRn33 commented on src/main/java/com/hello/foreverpet/service/CustomUserDetailsService.java
> +    private org.springframework.security.core.userdetails.User createUser(String username, UserInfo user) {
로그로 바꿨습니다!

2023-08-08 08:46 UTC, AiRn33 commented on src/main/java/com/hello/foreverpet/service/UserService.java
> +                .authorityName("ROLE_USER")
하드코딩 수정완료!

2023-08-08 08:47 UTC, AiRn33 commented on src/main/java/com/hello/foreverpet/service/UserService.java
> +        Long userNo = userInfoJpaRepository.save(user).getUserNo();
유저 Id가 좋아보여서 Id로 수정했습니당

2023-08-08 08:47 UTC, AiRn33 commented on src/main/java/com/hello/foreverpet/controller/UserController.java
> +    @Operation(summary = "로그인 테스트용",description = "로그인 테스트 진행.")
혹시 세큐리티라 하시면 어떤걸 말씀하시나요 ? 현재는 테스트중이라 프론트 단에서 문제없으면 시큐리티 처리필요한 URI 모아서 처리할 계획입니다!

2023-08-08 08:47 UTC, AiRn33 commented on src/main/java/com/hello/foreverpet/controller/UserController.java
> +    @Operation(summary = "로그인 어드민 테스트용",description = "로그인 어드민 테스트 진행.")
위와 동일하게 프론트 테스트용 API입니다 추후 삭제 예정입니다!

2023-08-08 08:48 UTC, AiRn33 commented on src/main/java/com/hello/foreverpet/domain/entity/UserInfo.java
>      private Long userNo;
Id 수정 완료

2023-08-08 08:53 UTC, AiRn33 commented on src/main/java/com/hello/foreverpet/domain/entity/UserInfo.java
>      private Boolean userDeleteYn;
userDeleteFlag로 일단 초안잡았습니다

2023-08-08 08:57 UTC, AiRn33 commented on src/main/java/com/hello/foreverpet/jwt/TokenProvider.java
> +    private final Logger logger = LoggerFactory.getLogger(TokenProvider.class);
수정완료!

2023-08-08 13:39 UTC, AlreadyBold commented on src/main/java/com/hello/foreverpet/controller/UserController.java
>          Long userNo = userService.userSignup(userSignupRequest);
userId추천드립니다 저도!

2023-08-08 13:40 UTC, AlreadyBold approved these changes

2023-08-09 03:59 UTC, cmong0516 approved these changes
수정하느라 고생하셨습니다!

2023-08-09 03:59 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/controller/UserController.java
> +    public ResponseEntity<Boolean> emailCheck(@RequestBody UserLoginRequest userLoginRequest){
네 감사합니다!

2023-08-09 04:48 UTC, merged