Alreadybold
Forever-Pet/foreverpet-backend pull request #121
Opened 2023-08-09 14:40 UTC by AlreadyBold

2023-08-09 14:55 UTC, AiRn33 approved these changes

2023-08-09 15:19 UTC, cmong0516 requested changes
1. 컨트롤러 에서 요청받는 OrderRequestBody 의 userNo 를 넣으신 이유가 있나요 ?
2. paymentName 을 날짜정보UUID 라고 하셨는데 그렇다면 입력받지 않고 요청받은 날짜로 UUID 를 생성할수도 있을거같은데 프론트에서 날짜정보 + UUID 로 된 값을 받으시는건가요 ?
3. OrderRequest 에는 배송주소 , 주문자 핸드폰번호 , 수령인 핸드폰 번호 가 있고 OrderRequestBody 에는 결제 주문 등의 모든 정보가 다 있는데 무언가 이름이 잘못 지어진거 같습니다.
4. Order Entity 와 Payment Entity 는 OneToOne 이시던데 연관관계의 주인은 누구인가요 ?
5. OrderProductService 를 OrderService  에서 분리하신 이유가 있나요 ?
6. OrderProductService 에서 코드를 조금더 간결하게 바꿀수 있을거같습니다.
7. OrderProductService 54번 줄에서 new Product() 를 사용하셨는데 findById 리턴값이 Optional<Product> 이니까 orelsethrow 나 ispresent 등으로 코드를 줄일수 있을거같습니다

2023-08-10 00:01 UTC, AlreadyBold commented on src/main/java/com/hello/foreverpet/controller/OrderController.java
> +    public ResponseEntity<String> createOrder(@RequestBody @Valid OrderRequestBody orderRequestBody) {
엇 수정하겠습니다 !

2023-08-10 00:07 UTC, AlreadyBold commented on src/main/java/com/hello/foreverpet/controller/OrderController.java
> +    public ResponseEntity<String> createOrder(@RequestBody @Valid OrderRequestBody orderRequestBody) {
코멘트 자체에 답글달기가 어려워서 여기에 남겨드립니다. 
1. 업데이트 전 엔티티의 식별자가 userNo 였고 토큰으로 바꿔야 하기때문에 수정하지 않았습니다.
2. payment_name은 이미 PG사에 다녀온 데이터(결제번호) 로써 PG사에서 중복이 불가합니다 . 로직 상 PG사 다녀온 뒤 그 데이터를 삽입하는 방식입니다. 그러니까 데이터 삽입시의 ( 날짜_UUID )가 아닌 PG사 전송시의 ( 날짜_UUID ) 인것입니다.
3. 피그마를 확인해보았는데 주문자핸드폰번호와 수령인 핸드폰번호가 전부 필수값으로 설정되어있습니다.
4. 주인은 OrderEntity 이므로 payment 먼저 생성 후 Order 안에 들어가는 형식입니다. 1:1 관계입니다.
5. OrderProduct 라는 엔티티가 있으므로 서비스로 나눈 것입니다만 수정의사있습니다.
6. 좀 더 생각해보겠습니다.
7. 수정 해서 커밋하겠습니다 !

2023-08-10 01:21 UTC, cmong0516 requested changes

2023-08-10 01:21 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/entity/Order.java
> +    private Payment paymentId;                      // 결제고유번호
Payment Entity 가 들어가는 것이라면
payment의 Id 는 Order.payment.id 로 조회할 것이니
그냥 payment 라고 하시는게 좋을거같습니다

2023-08-10 01:21 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/controller/OrderController.java
> +    public ResponseEntity<String> createOrder(@RequestBody @Valid OrderRequestBody orderRequestBody) {
OrderRequest 삭제
OrderRequestBody -> OrderRequest 로 이름 변경후
아래 필드들을 받음


OrderRequest

// 주문자 번호
customerPhoneNumber
// 수령자 번호
receiverPhoneNumber
// 배송주소
Address
// 결제정보
PaymentRequest
// 주문 상품 리스트
List<OrderProductRequest>


OrderProductListRequest -> OrderProductRequest


OrderRequestBody 내부 userId  삭제후
Order Entity 의 UserInfo 는 JWT 토큰으로 처리
OrderController 에서 HttpServlerRequest 받아서 처리


결제정보로 주문정보를 확인할수 있게 mappedBy 설정



이렇게 처리하면 요청객체도 줄고 한눈에 어떤 데이터들을 보내야할지 알기 쉬울거같습니다!

2023-08-10 07:48 UTC, AlreadyBold commented on src/main/java/com/hello/foreverpet/controller/OrderController.java
> +    public ResponseEntity<String> createOrder(@RequestBody @Valid OrderRequestBody orderRequestBody) {
요청하신 부분 처리하였습니다 !

다만 Header를 따로 받기로 햇습니다 .. 받는 데이터가 좀 많아서 ㅜ

2023-08-10 07:48 UTC, AlreadyBold commented on src/main/java/com/hello/foreverpet/domain/entity/Order.java
> +    private Payment paymentId;                      // 결제고유번호
변경 완료했습니다 !

2023-08-10 08:04 UTC, cmong0516 approved these changes
고생하셨습니다!
주문이랑 결제가 서로 잘 불러와지는지 테스트 해보시면 더 좋을거같아요

2023-08-10 09:02 UTC, merged