Sangbok
Forever-Pet/foreverpet-backend pull request #62
Opened 2023-07-11 11:32 UTC by AiRn33

UserInfo Entity 기본 설정 추가하였습니다

2023-07-11 11:42 UTC, cmong0516 requested changes
private 으로 보호해주는건 필요할거같습니다 !

2023-07-11 11:42 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/entity/UserInfo.java
> +public class UserInfo {
아래 필드들을 private 으로 보호해주면 좋을거같습니다 !

2023-07-11 11:42 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/entity/UserInfo.java
> +    String userAddress;
Address 는 제가 객체 만들겠습니다
나중에 Address 타입으로 부탁드려요 !

2023-07-11 11:42 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/entity/UserInfo.java
> +    Date userJoindate;
LocalDateTime 을 사용하는건 어떨까요 ?
또 Create 날짜를 원하시는거면 Auditing 을 사용해서
전체에 createdDate , modifidedDate 를 설정해서 처리하는것도 좋을거같습니다
이부분도 얘기해봅시다!

2023-07-11 12:10 UTC, AlreadyBold commented on src/main/java/com/hello/foreverpet/domain/entity/UserInfo.java
> +    String userAddress;
저도 Address 제외하고 다시 커밋해서 pull request 할게요 !

2023-07-11 12:11 UTC, AlreadyBold commented on src/main/java/com/hello/foreverpet/domain/entity/UserInfo.java
> +    Date userJoindate;
내일 회의시간에 얘기하는게 좋을것같습니다 ~!

2023-07-17 12:41 UTC, AiRn33 reviewed
확인했습니다

2023-07-17 12:41 UTC, AiRn33 commented on src/main/java/com/hello/foreverpet/domain/entity/UserInfo.java
> +public class UserInfo {
네 확인했습니다!

2023-07-18 07:05 UTC, cmong0516 approved these changes
Request changes 모두 반영 확인했습니다.

2023-07-18 07:24 UTC, AlreadyBold approved these changes

2023-07-18 14:05 UTC, merged