fix ( CreateOrder Request Body )
Forever-Pet/foreverpet-backend pull request #93
Opened 2023-07-31 15:36 UTC by AlreadyBold

fix ( OrderController ) : Request 형식 변경 
feat ( OrderRequest ) 
fix ( BillingInfo / OrderProcess ) : 수정요청 반영

2023-07-31 17:00 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/dto/OrderRequest.java
> +    private OrderInfoRequest orderInfoRequest;
OrderRequest 도 있고 OrderInfoRequest 도 있는데 두개를 이름만 봤을때는 좀 헷갈립니다
혹시 각 DTO 는 어떤 기능을 하는지 한번만 설명해주실수 있으신가요 ?!

2023-07-31 17:01 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/dto/request/BillingInfoRequest.java
> +    private String billingNm;
Nm 같은 축약보단 조금더 보자마자 무슨기능이구나! 알수있으면 좋을거같습니다!

2023-07-31 17:02 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/dto/request/OrderInfoRequest.java
> +    private Long userNo; // 주문한 유저번호
유저정보를 백에서 처리할지 프론트에서 받을지는
수요일에 결정되나요 ??

2023-07-31 17:02 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/dto/request/OrderInfoRequest.java
> +    private Long price; // 가격
상품갯수 , 가격 등을 개별적으로 처리하는게 좋지않을까 싶습니다!
결제라면 총 결제금액이면 되겠지만 주문은 세부적으로 나누어지면 좋지않을까 싶은데 어떠신가요 ?

2023-07-31 17:03 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/entity/OrderInfo.java
> +    private Long orderNo;               // 주문번호
orderNumber Or orderId 등의 이름을 추천해드리고 싶습니다!

2023-07-31 17:04 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/entity/OrderInfo.java
> +    private Long price;
이부분도 TotalPrice , 각 상품과 주문 갯수가 다를수 있으니
확인해볼수 있으면 좋을거같아요 !

2023-08-01 00:06 UTC, AlreadyBold commented on src/main/java/com/hello/foreverpet/domain/dto/OrderRequest.java
> +    private BillingInfoRequest billingInfoRequest;
1. 결제정보 추가 ( BillingInfo ) -> 2. 주문정보 추가 입니다
Request param / Request Body 등등 한가지의 파라미터 , 바디값만 받을 수 있어서 ( RequsetBody a , RequestBody b 안됨 )
OrderRequest 에 DTO 형식으로 바인딩 하기 위해 현재 파일을 생성하였습니다.

2023-08-01 00:06 UTC, AlreadyBold commented on src/main/java/com/hello/foreverpet/domain/dto/OrderRequest.java
> +    private OrderInfoRequest orderInfoRequest;
변수 및 자바파일이름 설정을 확실히 해보겠습니다 더 나은 가독성을 기대해주세요 !

2023-08-01 00:07 UTC, AlreadyBold commented on src/main/java/com/hello/foreverpet/domain/dto/request/OrderInfoRequest.java
> +    private Long userNo; // 주문한 유저번호
넵 ! 유저정보를 토큰으로 받을지 유저아이디만 받을지 토큰을 아이디로 변화하는과정을 백엔드에서 처리할지는 수요일날 정해보도록 하겠습니다.

2023-08-01 00:10 UTC, AlreadyBold commented on src/main/java/com/hello/foreverpet/domain/dto/request/OrderInfoRequest.java
> +    private Long price; // 가격
개별적인 상품 정보는 이미 엔티티에 onetomany로 설정되어있어서 괜찮을 것 같고 총 금액 및 총 수량 은  추가하는게 좋은것같다는 말씀이신가요 ? 
주문이 세부적으로 나누어진다는게 어떤의미인지 ㅜㅜ
총 금액 및 총 수량은 추가해서 수정하겠습니다!

2023-08-01 00:11 UTC, AlreadyBold commented on src/main/java/com/hello/foreverpet/domain/entity/OrderInfo.java
> +    private Long price;
아 상기해주신 내용이 a라는 제품 3개 + b라는 제품 1개 구매하고 이런경우에 발생하는 문제때문에 말해주신거군요 엔티티 정보를 변경해보도록하겠습니다!

2023-08-01 01:26 UTC, AlreadyBold commented on src/main/java/com/hello/foreverpet/domain/dto/OrderRequest.java
> +    private OrderInfoRequest orderInfoRequest;
OrderInfoRequest 는 OrderEntity 설정을 위해 필요한 값들이고 
OrderRequest 는 OrderInfoRequest , BillingInfoRequest , ProuductIdList 를 한번에 받아오기 위한 DTO 입니다.

2023-08-02 05:59 UTC, cmong0516 requested changes
조금 헷갈리는 부분들이 있어서 코멘트 남겨드렸습니다.
답글 달아주시면 확인해보겠습니다 !

2023-08-02 05:59 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/controller/OrderController.java
> +    private final OrderProductListService orderProductListService;
OrderProductListService 의 기능과 OrderService 와 분리하신 이유가 궁금합니다.

2023-08-02 05:59 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/dto/request/BillingInfoRequest.java
> +public class BillingInfoRequest {
billing 과 pay 를 같이 사용하는거보다 결제 라는걸 pay 로 통합하는건 어떠신가요 ?

2023-08-02 05:59 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/dto/request/OrderInfoRequest.java
> +public class OrderInfoRequest {
OrderInfoRequest 는 주문한 유저정보를 받는건가요
아니면 주문유저와 주문정보를 담는건가요 ?

2023-08-02 05:59 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/dto/request/OrderProductListRequest.java
> +public class OrderProductListRequest {
상품번호를 받는데 Product 가 또 존재하면 같은 정보를 두곳에서 받는건가요 ?

2023-08-02 05:59 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/entity/OrderInfo.java
> +    private List<OrderProductList> orderProducts; // 상품번호 ( FK 설정 , 한개의 주문정보에 많은 상품이 있을 수 있음 )
List 안에 List 가 존재하는건가요 ?

2023-08-02 07:18 UTC, AlreadyBold commented on src/main/java/com/hello/foreverpet/controller/OrderController.java
> +    private final OrderProductListService orderProductListService;
OrderService 는 주문정보 생성입니다.
OrderProductListService 는 각각 개별 상품에 대한 정보 생성입니다.

2023-08-02 15:37 UTC, cmong0516 requested changes
수정해주시면 조금더 좋을거같은 부분과
궁금한점 코멘트로 남겨놓았습니다.
답글 남겨주시면 체크다시 해보겠습니다!

2023-08-02 15:37 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/controller/OrderController.java
> +    public ResponseEntity<Long> createOrder(@RequestBody @Valid CreateOrderRequest createOrderRequest) {
CreateOrderRequest 라 하면 주문 요청을 생성한다 라는 생각이 드는데
주문 요청을 받는 객체라면 OrderRequest 가 맞지 않을까 싶습니다!

2023-08-02 15:37 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/dto/CreateOrderRequest.java
> +public class CreateOrderRequest {
위에 코멘트 남겨드렸습니다!

2023-08-02 15:37 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/dto/CreateOrderRequest.java
> +    public CreateOrderRequest() {
이 생성자는 어떻게 사용하려고 만들어두신건가요 ?

2023-08-02 15:37 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/dto/request/OrderInfoRequest.java
> +    private PaymentInfo paymentId;                  // 주문 정보
주석이 잘못된거같습니다 결제정보로 추측됩니다!

2023-08-02 15:37 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/dto/request/OrderInfoRequest.java
> +    public OrderInfoRequest () {
이 생성자는 어떤이유로 만들어두신건가요 ?

2023-08-02 15:37 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/dto/request/OrderInfoRequest.java
> +                .userNo(this.userNo)
userId 는 어떨까 싶습니다!

2023-08-02 15:37 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/dto/request/OrderProductListRequest.java
> +    private Product orderProduct;                   // 상품정보
OrderProductListRequest 라면 주문상품리스트를 받아오는것같은데
프론트에서는 Product Entity 에 대한 정보를 모르지 않을까요 ?
또 위에 상품번호가 존재하는데 Product 가 또 존재한다면 productId 가 두번 들어간다고 생각합니다.

2023-08-02 15:37 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/dto/request/PaymentInfoRequest.java
> +    public PaymentInfo toEntity() {
주문 = OrderInfo 결제 = PaymentInfo 라고 지으셨는데
Order 가 주문에 대한 Entity 이고 Payment 가 결제에 관한 Entity 라는걸 알고있는데 Info 를 생략하는건 어떠신가요 ?

2023-08-02 15:37 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/entity/OrderInfo.java
> +    private Long userNo;                            // 주문한 유저번호 ( fk 설정할 경우 유저정보 조회 시 데이터 과다 ) // Long vs Entity 맵핑 관계 조회 데이터 분석
Order 에 주문한 유저의 Entity 가 들어있는건 어떨까 합니다!

2023-08-02 15:37 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/entity/OrderInfo.java
> +    private List<OrderProduct> orderProductList;   // 상품번호 ( FK 설정 , 한개의 주문정보에 많은 상품이 있을 수 있음 )  // querydsl patch join
주석이 잘못되어있는거같습니다!

2023-08-02 15:37 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/entity/OrderInfo.java
> +    @Builder
@Id 로 설정하신 orderId는 자동으로 생성될텐데 @Builder 에 넣으신 이유가 있으신가요 ??
totalPrice 부분을
this.totalPrice += orderProductList.get(i).getOrderProductPrice(); 로 바꾸면
조금더 코드가 간결해질거같습니다.

2023-08-02 15:37 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/entity/OrderProduct.java
> +public class OrderProduct {
주문한 상품의 가격 * 갯수 로 현재 상품의 총 주문에 대한 가격정보도 나타나면 좋을거같아요

2023-08-02 15:37 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/service/OrderProductService.java
> +        for (int i =0; i< orderProductRequest.size(); i++ ) {
gpt 센세가 간결한 코드를 알려주셨습니다
Map<String, Integer> productIdMap = orderProductRequest.stream()
    .collect(Collectors.toMap(
        OrderProduct::getOrderProductId,
        OrderProduct::getOrderProductAmount,
        Integer::sum
    ));

2023-08-02 15:37 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/service/OrderProductService.java
> +            Product getOrderProductInfo = new Product();
Id 로 product 를 찾는 과정을 위에서 먼저 처리한다면
전체 처리과정을 조금더 줄일수 있지 않을까요 ?

2023-08-04 02:54 UTC, cmong0516 requested changes
OrderRequestBody 라는 객체로
PaymentRequest(결제정보) ,OrderRequest(주문정보) , List<OrderProductListRequest>(주문상품정보) 세가지 정보를 받아서 처리하시는군요
중간중간 궁금한점 코멘트 남겨드렸습니다 답글달아주세요!

2023-08-04 02:54 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/dto/request/OrderProductRequest.java
> +    private Product orderProduct;                       // 상품정보
프론트에서 요청받는 값이라면 엔티티로는 받을수 없을거같습니다!

2023-08-04 02:54 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/dto/request/OrderRequest.java
> +    private Long userNo;                            // 주문한 유저번호
userId 어떠신가요 !
또는 저는 HttpServletRequest 의 Header 토큰에서 직접 유저정보를 가져오는 방법을 택해봤습니다.
그렇게 하면 로그인한 본인만이 주문이 가능하니까요 !

2023-08-04 02:54 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/dto/request/OrderProductListRequest.java
> +public class OrderProductListRequest {
하나의 상품에 대한 주문을 객체로 표시하신건가요 ?
그렇다면 List 를 제외하시는건 어떨까요 ?

2023-08-04 02:54 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/dto/request/OrderProductRequest.java
> +    private Product orderProduct;                       // 상품정보
사용중단 이라고 주석을 달아놓으신건가요 ??

2023-08-04 02:54 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/entity/Order.java
> +    private Long userNo;                            // 주문한 유저번호
유저도 Entity 로 들어가면 어떨까요 ?!

2023-08-05 13:34 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/dto/request/OrderInfoRequest.java
> +    private Long price; // 가격
따로 설명드린거처럼 각각의 orderItem 들을 만들고 orderItem 들을 List 로 담는것인데
이때 orderItem 내부 필드에 상품의 가격 , 갯수 , 이 상품 주문의 가격 을 표시하는것을 말씀드린겁니다!

2023-08-05 13:35 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/controller/OrderController.java
> +    private final OrderProductListService orderProductListService;
둘다 주문을 담당하는 서비스라면 하나의 서비스에서 처리해도 괜찮지 않을까요 ?

2023-08-07 07:17 UTC, cmong0516 approved these changes

2023-08-07 07:17 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/service/OrderProductService.java
> +            Product getOrderProductInfo = new Product();
받은 아이디 값들로 위의 과정을 처리하고 있으신데
그 값들중에 productJpaRepository.findbyId 의 값이 Null 이라면
조금더 과정이 줄어들거같아서 위에서 처리하는건 어떠신지 여쭤본겁니다!

2023-08-07 07:17 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/entity/OrderProduct.java
> +public class OrderProduct {
네 갑사합니다!

2023-08-07 07:17 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/entity/OrderInfo.java
> +    @Builder
감사합니다!

2023-08-07 07:17 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/entity/OrderInfo.java
> +    private List<OrderProduct> orderProductList;   // 상품번호 ( FK 설정 , 한개의 주문정보에 많은 상품이 있을 수 있음 )  // querydsl patch join
넵!

2023-08-07 07:17 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/entity/OrderInfo.java
> +    private Long userNo;                            // 주문한 유저번호 ( fk 설정할 경우 유저정보 조회 시 데이터 과다 ) // Long vs Entity 맵핑 관계 조회 데이터 분석
네 맞습니다. 또 어떤 기능을 구현할때 필요할수 있으니 열어두자는 의견입니다!

2023-08-07 07:17 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/dto/request/PaymentInfoRequest.java
> +    public PaymentInfo toEntity() {
감사합니다!

2023-08-07 07:17 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/dto/request/OrderProductListRequest.java
> +    private Product orderProduct;                   // 상품정보
옙!

2023-08-07 07:17 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/dto/request/OrderInfoRequest.java
> +                .userNo(this.userNo)
userNo 보다는 userId 또는 userNumber 가 좋지않을까 합니다
수정하신다면 번거롭지만 전체를 .... ㅠ

2023-08-07 07:17 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/dto/CreateOrderRequest.java
> +    public CreateOrderRequest() {
제 새 상품 등록쪽은 별도의 빈 생성자를 생성하지 않아도 상품등록이 되던데
어떤 차이가 있을까요 ?!

2023-08-07 07:17 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/controller/OrderController.java
> +    public ResponseEntity<Long> createOrder(@RequestBody @Valid CreateOrderRequest createOrderRequest) {
order request 와 orderRequestBody 는 각각 어떤 기능인가요 ?!

2023-08-07 07:17 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/dto/request/BillingInfoRequest.java
> +public class BillingInfoRequest {
감사합니다!

2023-08-07 07:17 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/controller/OrderController.java
> +    private final OrderProductListService orderProductListService;
아하 서비스를 나누는 기준을 엔티티로 하셨군요
전 엔티티에 따라 나누는건 Repository 라고 보고
같은 주문에 관한 내용이라면 한 서비스에서 하는건 어떨까 하고 여쭤보았습니다

2023-08-07 07:17 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/entity/OrderInfo.java
> +    private Long price;
감사합니다!

2023-08-07 07:17 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/dto/OrderRequest.java
> +    private BillingInfoRequest billingInfoRequest;
이부분도 payment 로 변경해주셨나요 ?!

2023-08-08 00:30 UTC, AlreadyBold commented on src/main/java/com/hello/foreverpet/domain/dto/OrderRequest.java
> +    private BillingInfoRequest billingInfoRequest;
네 그렇습니다.

2023-08-08 00:31 UTC, AlreadyBold commented on src/main/java/com/hello/foreverpet/controller/OrderController.java
> +    public ResponseEntity<Long> createOrder(@RequestBody @Valid CreateOrderRequest createOrderRequest) {
orderRequest => 주문정보를 다루는 부분이고

orderRequestBody => 프론트에서 넘어오는 데이터를 다루는 부분입니다.

2023-08-08 01:44 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/domain/dto/OrderRequest.java
> +    private BillingInfoRequest billingInfoRequest;
감사합니다!

2023-08-08 02:04 UTC, cmong0516 commented on src/main/java/com/hello/foreverpet/controller/OrderController.java
> +    public ResponseEntity<Long> createOrder(@RequestBody @Valid CreateOrderRequest createOrderRequest) {
orderRequestBody : 주문정보 , 결제정보 , 주소 등을 받는 객체이고
orderRequest : orderRequestBody 에서 주문정보만을 나타낸것

이 맞다면 orderRequestBody 를 orderAndPaymentRequest 로 하면 어떤가요 ?!

2023-08-09 04:40 UTC, merged